### ISSUE TITLE
Where does the youtube channel comes in?

### ISSUE THREAD

**Issue by BuddhiLW** [Wllew4/obs-autoupload#1]
Hello, 

As I followed the steps to use the script, I missed any relation to my youtube channel. 

Should I chose the redirect URL, in the OAuth etc from Google and Twitch to be my URI pointing to my youtube channel? (In my case, https://www.youtube.com/channel/UCcDTD0VMlN2tGA7sDVZllRw)

**Comment by Wllew4** [comment]
Hello! When the script runs (after a stream has ended in OBS) you should be prompted to log in to the app with a Google account. You will be given a code to paste into the app. Your login is cached after the first time.

I should warn you that I have not maintained this project for several months, and am planning on either revamping or retiring it sooner or later. I have given it a run tonight for the first time in awhile and confirmed that it does still work as intended.

I hope this answers your question! Feel free to open up a new issue if you get stuck on anything else.
